CREATE DATABASE QUANLYBANHANG;
USE QUANLYBANHANG;
CREATE TABLE CUSTOMER(
    cID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cNAME VARCHAR(10) NOT NULL ,
    cAGE INT NOT NULL
);
CREATE TABLE `ORDER`(
    oID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cID INT NOT NULL ,
    FOREIGN KEY (cID) REFERENCES CUSTOMER(cID),
    oDATE DATETIME,
    oTotalPrice INT
);
CREATE TABLE PRODUCT(
    pID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    pNAME VARCHAR(20) NOT NULL ,
    pPRICE INT
);
CREATE TABLE ORDER_DETAIL(
    oID INT,
    pID INT,
    PRIMARY KEY (oID, pID),
    FOREIGN KEY (oID) REFERENCES `ORDER`(oID),
    FOREIGN KEY (pID) REFERENCES PRODUCT(pID),
    odQTY INT
);