CREATE DATABASE DEMO;

USE DEMO;

CREATE TABLE PRODUCTS(
ID INT AUTO_INCREMENT PRIMARY KEY,
PRODUCT_CODE VARCHAR(20) NOT NULL,
PRODUCT_NAME VARCHAR(55),
PRODUCT_PRICE DOUBLE,
PRODUCT_AMOUNT INT,
PRODUCT_DESCRIPTION VARCHAR(200),
PRODUCT_STATUS VARCHAR(55)
);

INSERT INTO PRODUCTS
VALUES (1, 'sp01', 'Clear men', 50000, 50, 'dầu gội đầu', 'còn hàng'),
       (2, 'sp02', 'Hảo hảo', 4000, 200, 'aciecook việt nam', 'còn hàng'),
       (3, 'sp03', 'gấu đỏ', 3500, 50, 'gấu đỏ ngon mê ly', 'còn hàng'),
       (4, 'sp04', 'Omachi', 8000, 60, 'dai ngon từng sợi', 'gần hết hạn'),
       (5, 'sp05', 'Custas', 55000, 20, 'orion', 'còn hàng'),
       (6, 'sp06', 'chocopie', 30000, 15, 'orion', 'còn hàng'),
       (7, 'sp07', 'Xmen', 80000, 23, 'Xmen đàn ông đích thực', 'còn hàng'),
       (8, 'sp08', 'Romano', 90000, 21, 'Romano thơm tho lịch lãm', 'còn hàng'),
       (9, 'sp09', 'Hảo hảo', 3500, 50, 'Hảo hảo mỳ được ưu chuộng nhất', 'còn hàng');
       
CREATE UNIQUE INDEX PRODUCT_CODE_IDX ON PRODUCTS(PRODUCT_CODE);

CREATE UNIQUE INDEX PRODUCT_NAME_PRICE_IDX ON PRODUCTS(PRODUCT_NAME, PRODUCT_PRICE);

EXPLAIN SELECT * FROM PRODUCTS
WHERE PRODUCT_CODE = 'sp01';

EXPLAIN SELECT * FROM PRODUCTS
WHERE PRODUCT_NAME = 'Hảo hảo' AND PRODUCT_PRICE = 3500;

CREATE VIEW PRODUCTS_VIEW AS
SELECT PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STATUS
FROM PRODUCTS;

SELECT * FROM PRODUCTS_VIEW;

CREATE OR REPLACE VIEW PRODUCTS_VIEW AS
SELECT PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STATUS
FROM PRODUCTS
WHERE PRODUCT_STATUS = 'còn hàng';

DROP VIEW PRODUCTS_VIEW;

DELIMITER //
CREATE PROCEDURE FIND_ALL_PRODUCT()
BEGIN
  SELECT * FROM PRODUCTS;
END //
DELIMITER ;

CALL FIND_ALL_PRODUCT();

DELIMITER //
CREATE PROCEDURE ADD_NEW_PRODUCT(IN `CODE` VARCHAR(20),
								IN `NAME` VARCHAR(55),
                                IN PRICE DOUBLE,
                                IN AMOUNT INT)
BEGIN
	INSERT INTO PRODUCTS(PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_AMOUNT)
    VALUES (`CODE`, `NAME`, PRICE, AMOUNT);
END //
DELIMITER ;

CALL ADD_NEW_PRODUCT('sp11', 'Aone', 35000, 50);
CALL FIND_ALL_PRODUCT();

DELIMITER //
CREATE PROCEDURE UPDATE_PRODUCT_NAME_BY_ID(IN INPUT_ID int,
                                           IN `NAME` varchar(55))
BEGIN
    UPDATE PRODUCTS SET PRODUCT_NAME = `NAME` WHERE ID = INPUT_ID;
END //
DELIMITER ;

CALL UPDATE_PRODUCT_NAME_BY_ID(9, 'Mì ba miền');
CALL FIND_ALL_PRODUCT();

DELIMITER //
CREATE PROCEDURE DELETE_PRODUCT_BY_ID(IN INPUT_ID int)
BEGIN
    DELETE FROM PRODUCTS where ID = INPUT_ID;
END //
DELIMITER ;

CALL DELETE_PRODUCT_BY_ID(9);
CALL FIND_ALL_PRODUCT();